#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin

CONFIGPATH=/etc/homegear
DAEMON=/usr/bin/homegear
PIDPATH=/var/run/homegear
LOCKPATH=/run/lock
PIDFILE=$PIDPATH/homegear.pid
STATICPATH=/usr/share/homegear
DBPATH=/var/lib/homegear
LOGPATH=/var/log/homegear

test -x $DAEMON || exit 150

if [ -r /etc/default/homegear ]; then
        . /etc/default/homegear
fi

RUNASUSER=homegear
RUNASGROUP=homegear

HOMEGEAR_OPTS="$HOMEGEAR_OPTS -u $RUNASUSER -g $RUNASGROUP -d"

case $1 in
        start)
			killall synousbmodemd
			STATUS=`ps | grep -c homegear`
			if [ $STATUS -eq 2 ]; then
				exit 0
			fi
			if test ! -d $PIDPATH; then 
				mkdir -p $PIDPATH
			fi
			chown -R $RUNASUSER:$RUNASGROUP $PIDPATH
			chmod -R 750 $PIDPATH

			if test ! -d $LOCKPATH; then 
				mkdir -p $LOCKPATH
			fi
			chmod 777 $LOCKPATH

			if test ! -d $DBPATH; then 
				mkdir -p $DBPATH
			fi
			chown -R $RUNASUSER:$RUNASGROUP $DBPATH
			chmod 750 $DBPATH
			chmod 640 $DBPATH/db.sql
			chmod 550 $DBPATH/scripts
			chmod 550 $STATICPATH/firmware
			chmod 440 $STATICPATH/firmware/*
			chmod 550 $STATICPATH/firmware/*.sh
			chmod -R 550 $DBPATH/modules

			if test ! -d $LOGPATH; then
				mkdir -p $LOGPATH
			fi
			chown -R $RUNASUSER:$RUNASGROUP $LOGPATH
			chmod -R 750 $LOGPATH

			if test ! -e /usr/share/homegear/firmware/0000.00000069.fw; then
				echo "Downloading current firmware updates..."
				$STATICPATH/firmware/GetFirmwareUpdatesHomeMaticBidCoS.sh
			fi

            $DAEMON -p $PIDFILE $HOMEGEAR_OPTS
            ;;
        stop)
            if test -e $PIDFILE; then
	        	PID=`cat $PIDFILE`
	        	PROCESSCOUNT=`ps | grep -c $PID`
	        	if [ $PROCESSCOUNT -ne 1 ]; then
	        		kill -15 $PID
	        	fi
	        	while [ $PROCESSCOUNT -ne 1 ]; do
	        		sleep 1
	        		PROCESSCOUNT=`ps | grep -c $PID`
	        	done
			fi
            ;;
        status)
			STATUS=`ps | grep -c homegear`
			if [ $STATUS -ge 2 ]; then
				exit 0
			fi
			exit 3
			;;
		log)
			echo "/var/log/homegear/homegear.log"
			;;
        restart|force-reload)
                $0 stop && sleep 2 && $0 start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 2
                ;;
esac

exit 0
